language: perl
dist: xenial
perl:
        - "5.28"
sudo: false
addons:
          apt:
                update: true
                sources:
                        - sourceline: 'deb http://mirrors.kernel.org/ubuntu/ eoan main universe'
                packages:
                        - sasl2-bin
                        - libswitch-perl
                        - cyrus-imapd
                        - cyrus-clients
                        - cyrus-admin
                        - 389-ds
                        - libmozilla-ldap-perl
install:
        true
before_script:
        - setup-ds -f travis/ldap.inf
        - sistemctl restart dirsrv     
script: true
after_failure: true
#          - cat /home/travis/.cpanm/work/*/build.log
