language: perl
perl:
        - "5.16"
sudo: false
before_install:
        - sudo apt-get install -y libswitch-perl
        - sudo apt-get install -y sasl2-bin
        - echo "deb http://mirrors.kernel.org/ubuntu/ eoan main universe" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
addons:
          apt:
                update: true
                source:
                        - sourceline: 'deb http://mirrors.kernel.org/ubuntu/ eoan main universe'
                packages:
                        - cyrus-imapd
                        - cyrus-clients
                        - cyrus-admin
install:
        true
before_script: true
script: true
after_failure:
          - cat /home/travis/.cpanm/work/*/build.log
