language: perl
dist: xenial
perl:
        - "5.16"
sudo: false
addons:
          apt:
                update: true
                source:
                        - sourceline: 'deb http://mirrors.kernel.org/ubuntu/ eoan main universe'
                packages:
                        - sasl2-bin
                        - libswitch-perl
                        - cyrus-imapd
                        - cyrus-clients
                        - cyrus-admin
install:
        true
before_script: true
script: true
after_failure: true
#          - cat /home/travis/.cpanm/work/*/build.log
