language: perl
dist: xenial
perl:
        - "5.28"
sudo: false
addons:
        apt:
                update: true
                sources:
                        - sourceline: 'deb http://mirrors.kernel.org/ubuntu/ eoan main universe'
                packages:
                        - sasl2-bin
                        - cyrus-imapd
                        - cyrus-pop3d
                        - cyrus-clients
                        - cyrus-admin
                        - 389-ds
                        - cpanminus
                        - libmozilla-ldap-perl
                        # Scripts dependencies
                        - libswitch-perl
                        - libconfig-inifiles-perl
                        - libdata-validate-domain-perl
                        - libdate-calc-perl
                        - libwww-perl
                        - libmail-imaptalk-perl
                        - libnet-ldap-perl
                        - libtemplate-plugin-posix-perl
                        - libproc-daemon-perl
                        - libstring-scanf-perl
                        # - libsys-syslog-perl (already inclided in perl)
                        - liburi-perl
                        # - libunicode-imaputf7-perl (to make by source)
                        - libperl-version-perl
before_install:
        - sudo sed -i 's/checkHostname {/checkHostname {\nreturn();/g' /usr/lib/x86_64-linux-gnu/dirsrv/perl/DSUtil.pm
        - sudo setup-ds --silent --file=travis/ldap.inf
        - ldapadd -D "cn=directory manager" -w ldapassword -vvv -f travis/user.ldif
        # - cat /etc/imapd.conf
        # - cat /etc/default/saslauthd
        # - cat /etc/default/cyrus-imapd
        - sudo sed -i 's|MECHANISMS=.*|MECHANISMS="ldap"|' /etc/default/saslauthd
        - sudo sed -i 's|START=no|START=yes|' /etc/default/saslauthd
        - sudo cp travis/saslauthd.conf /etc/
        - sudo systemctl restart saslauthd
        - sudo cp travis/annoIMAP.conf /etc/
        - sudo cp travis/imapd.conf /etc/
        - sudo sed -i -r 's|^\t+nntp\t+.*||' /etc/cyrus.conf
        - sudo sed -i -r 's|^\t+http\t+.*||' /etc/cyrus.conf
        - sudo mkdir -pv /maildata/example.com/maildata1
        - sudo mkdir -pv /maildata/example.com/maildata2
        - sudo chown -R cyrus:mail /maildata
        - sudo systemctl restart cyrus-imapd
        - sudo systemctl status saslauthd.service -l
install:
        - sudo cpanm -v Unicode::IMAPUtf7
        - cp -p cyr_scripts.ini-default cyr_scripts.ini
        - sudo chown cyrus:mail cyr_scripts.ini
        - sudo chown cyrus core.pl
        - sed -i "s|\/usr\/local\/cyr_scripts\/|$PWD\/|" *.pl
        - sed -i "s|\/usr\/local\/cyr_scripts|$PWD|" cyr
        - sed -i 's|use feature|use experimental|' *.pl
        - export PATH=$PATH:/usr/lib/cyrus/bin
        - sudo sed -i -r -e '/^\s*Defaults\s+secure_path/ s[=(.*)\"[=\1:/usr/lib/cyrus/bin\"[' /etc/sudoers
        - sudo mkdir /run/cyr_setPartitionAnno
        - sudo chown cyrus:mail /run/cyr_setPartitionAnno
        - sudo chmod 644 core.pl cyr_scripts.ini
        # We need to own the home script folder to write conf with Perl
        - sudo chgrp mail ../cyr_scripts
        - sudo chmod 775 ../cyr_scripts

before_script:
        - sudo testsaslauthd -u marco.favero@example.com -p password -f /var/run/saslauthd/mux
        - sudo chmod 700 travis/test_suite.sh

script:
        - travis/test_suite.sh

after_failure:
        - cat travis/test.log
        - sudo ls -l    /home/travis/build/falon/cyr_scripts /home/travis/build/falon /home/travis/build  /home/travis  /home
