language: perl
dist: xenial
perl:
        - "5.28"
sudo: false
addons:
          apt:
                update: true
                sources:
                        - sourceline: 'deb http://mirrors.kernel.org/ubuntu/ eoan main universe'
                packages:
                        - sasl2-bin
                        - cyrus-imapd
                        - cyrus-clients
                        - cyrus-admin
                        - 389-ds
                        - libmozilla-ldap-perl
                          # Scripts dependencies
                          #- libswitch-perl
                          #- libconfig-inifiles-perl
                          #- libdata-validate-domain-perl
                          #- libdate-calc-perl
                          #- libwww-perl
                          #- libmail-imaptalk-perl
                          #- libnet-ldap-perl
                          #- libtemplate-plugin-posix-perl
                          #- libproc-daemon-perl
                          #- libstring-scanf-perl
                          #- libsys-syslog-perl
                          #- liburi-perl
                          #- libunicode-imaputf7-perl
                          #- libperl-version-perl
before_install:
        - sudo sed -i 's/checkHostname {/checkHostname {\nreturn();/g' /usr/lib/x86_64-linux-gnu/dirsrv/perl/DSUtil.pm
        - sudo setup-ds --silent --file=travis/ldap.inf
        - ldapadd -D "cn=directory manager" -w ldapassword -vvv -f travis/user.ldif
          #- cat /etc/imapd.conf
          #- cat /etc/default/saslauthd
          #- cat /etc/default/cyrus-imapd
        - sudo sed -i 's|MECHANISMS=.*|MECHANISMS="ldap"|' /etc/default/saslauthd
        - sudo cp travis/saslauthd.conf /etc/
        - sudo systemctl start saslauthd
        - sudo cp travis/annoIMAP.conf /etc/
        - sudo cp travis/imapd.conf /etc/
        - sudo mkdir -pv /maildata/example.com/maildata1
        - sudo mkdir -pv /maildata/example.com/maildata2
        - sudo systemctl restart cyrus-imapd
        - sudo systemctl status saslauthd.service
install:
        true
before_script:
        - sudo testsaslauthd -u marco.favero@example.com -p password -f /var/run/saslauthd/mux
script:
        - cpanm --installdeps --notest .
        - cat /home/travis/.cpanm/work/*/build.log
        - ./cyr_version.pl
after_failure: true
#          - cat /home/travis/.cpanm/work/*/build.log
