language: perl
perl:
        - "5.16"
sudo: false
before_install:
        - apt-get install -y libswitch-perl
        - apt-get install -V -y cyrus-imapd cyrus-clients cyrus-admin sasl2-bin
addons:
          apt:
                update: true
                source:
                        - sourceline: 'deb http://it.archive.ubuntu.com/ubuntu/ eoan main universe'
install:
        true
before_script: true
script: true
after_failure:
          - cat /home/travis/.cpanm/work/*/build.log
