language: perl
perl:
        - "5.16"
sudo: false
before_install:
        - sudo apt-get install -y libswitch-perl
        - sudo apt-get install -y sasl2-bin
addons:
          apt:
                update: true
                source:
                        - sourceline: 'deb http://mirrors.kernel.org/ubuntu/ eoan main universe'
                packages:
                        - cyrus-imapd-3.0.8
                        - cyrus-clients-3.0.8
                        - cyrus-admin-3.0.8
install:
        true
before_script: true
script: true
after_failure:
          - cat /home/travis/.cpanm/work/*/build.log
