#!/bin/bash
HOMEDIR=/usr/local/cyr_scripts
usage() {
	echo -en "\n\e[33mThis is a shortcut to interface with cyradm.\n Usage $0 <servername>\e[39m\n\n";
	exit 1
}

SERVER=$1
[ "$#" -eq 1 ] || {
	SERVER=`sed -nr "/^\[imap\]/ { :l /^server\s*[ ]*=/ { s/.*=[ ]*//; s/\s*#.*//; p; q;}; n; b l;}" $HOMEDIR/cyr_scripts.ini`
	echo -en "\n1 argument required, with server name where to connect, $# provided.\nAssuming \e[33m$SERVER\e[39m as server, as provided in config file.\n\n";
}

if [ "$1" == '--help' ] || [ "$1" == '-h' ] || [ "$1" == 'help' ]; then
	usage;
	exit 1;
fi
USER=`sed -nr "/^\[imap\]/ { :l /^user\s*[ ]*=/ { s/.*=[ ]*//; s/\s*#.*//; p; q;}; n; b l;}" $HOMEDIR/cyr_scripts.ini`
echo -en "\nConnecting to server <\e[33m$SERVER\e[39m> with user <\e[33m$USER\e[39m>...\n"
/usr/bin/cyradm -u $USER --auth PLAIN $SERVER
